# http://localhost:8080/h2-console
# jdbc url: jdbc:h2:mem:testdb
# insert into snack_machine_dto (id, cent_count, dime_count, quarter_count, dollar_count, five_dollar_count, twenty_dollar_count, transaction_cent_count, transaction_dime_count, transaction_quarter_count, transaction_dollar_count, transaction_five_dollar_count, transaction_twenty_dollar_count) values (1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0);
spring:
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace